appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Kehf4RkuIjjgXUGmVujGydJGFFtYljp9ofM/lqlVOX6VIyzcOtUGpZQhs1jHKA5r3dnoeq/46QHuWalCyWAoyhGydSpMU7wIecrJ5eSknwjYVOq6A40YpfFfDG7bLGw3JDKISfrjQiFYipx9vK8YF6HasaHGNdqxz4GbVuQ3IJ+j2DZ67oNcLzu9kxYC/RZk+VpsSUBt0ppLGgjdt+W7M41pjcrRiYphGEzF04ccMQnhqONCVKOmCyKVctGRAV1DRiZ3Grfbut05oAJGuFDLV77KszUctubJSm2E3a/oH6mQUmJs0vJv9n1HInC7Lon+38ZN0GfiW1Kkm8o/OhEGnt/ZeFJmk1GsUwD6fcSGge6PeFqV87iEDeoPhF5t3JVqyCAsKcYokhd9bHSCpELOL8zWdNtLBTfmIeEz8ztnLAnGZyUy6nm0HIIKZpZQzLaFKzRF52/NfN/oZuo7XcUBPyTt4oebL32t/V4pIiJAgivQoZok/T/PdaB2fGKkRXGbKeV8AXANv6QYekKGJ2pzrEJDvjhms/H57uKnQmgAepPw+oErXHFbe++RDm9phdMFTzNfRvS157ztwJXqwpeEQcxJYfFmAFy7e1QPKQsgYK0D7BBhcI78+cPRA9fduLb5+Ed6Lr3k7FhBzB6KgccLucbD8VcHEXbaTH+AIGfbjLw=}
